version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mfnextgencon
    ports:
      - "8081:8081"
    volumes:
      - ./:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    networks:
      - ci_network
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: mfnextgendbcon
    environment:
      MYSQL_ROOT_PASSWORD: root_password        # This sets the root password
      MYSQL_DATABASE: mfnextgen_test_db         # The database to create
      MYSQL_USER: mfnextgen_ci4_user            # Use a different username
      MYSQL_PASSWORD: ci4password               # Password for the new user
    ports:
      - "3307:3306"
    networks:
      - ci_network

networks:
  ci_network:
    driver: bridge
